const columns = [
  {name: "Nombre", uid: "name", sortable: true},
  {name: "Edad", uid: "age", sortable: true},
  {name: "Rol", uid: "role", sortable: true},
  {name: "Equipo", uid: "team"},
  {name: "Email", uid: "email"},
  {name: "Estado", uid: "status", sortable: true},
  {name: "Cargo", uid: "actions"},
];

const statusOptions = [
  {name: "Activo", uid: "activo"},
  {name: "inactivo", uid: "inactivo"},
  {name: "Vacaciones", uid: "vacaciones"},
];

const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "29",
    avatar: "https://i.pinimg.com/564x/66/54/03/665403d22f04e5b4f7bf06d1d96e8c36.jpg",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Trabajador",
    team: "Trabajador",
    status: "inactivo",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "Trabajador",
    team: "Trabajador",
    status: "vacaciones",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "Trabajador",
    team: "Trabajador",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "activo",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Trabajador",
    team: "Trabajador",
    status: "inactivo",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "Trabajador",
    team: "Trabajador",
    status: "vacaciones",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "Trabajador",
    team: "Trabajador",
    status: "inactivo",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "Trabajador",
    team: "Trabajador",
    status: "inactivo",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Trabajador",
    team: "Trabajador",
    status: "inactivo",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Trabajador",
    team: "Trabajador",
    status: "activo",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export {columns, users, statusOptions};
